// All Salado food truck data — shared by the generator script
const APPSYNC_URL = "https://d2zlzofjerf4hd6gltypy2rnlm.appsync-api.us-east-1.amazonaws.com/graphql";
const API_KEY     = "da2-6l2dtmahczbbnlp3m2vmgihqby";

const trucks = [
  {
    id: 'SylviasTacos', subdomain: 'sylviastacos',
    name: "Sylvia's Tacos", emoji: '🌮',
    tagline: 'Authentic Homemade Tacos · Salado, TX',
    heroDesc: 'The authentic hometown taco truck of Salado. Handmade corn and flour tortillas made fresh every morning.',
    about: "Sylvia's Tacos is Salado's beloved breakfast taco institution. Every tortilla is handmade fresh daily — corn and flour — and the fillings are as authentic as it gets. Whether it's a classic egg & cheese or a hearty brisket taco, this is the real deal.",
    address: '841 N. Main St., Salado, TX 76571', phone: '(254) 718-1873',
    hours: [['Mon–Sat','7:00 AM – 1:00 PM'],['Sunday','Closed']],
    happyHour: null,
    primary: '#C0392B', primaryDark: '#922B21', accent: '#F39C12',
    textOnPrimary: '#FFFFFF',
    source: 'SylviasTacos', password: 'Sylvias2025!',
    features: ['Handmade Tortillas','Breakfast Tacos','Authentic Recipes','Cash & Card'],
    categories: ['Breakfast Tacos','Gorditas','Tortas','Drinks'],
    menu: [
      { itemId:'ST-001', category:'Breakfast Tacos', name:'Egg & Cheese Taco', price:2.50, description:'Scrambled egg, cheddar cheese, fresh tortilla', available:true, customizationOptions:JSON.stringify(['Corn Tortilla','Flour Tortilla']) },
      { itemId:'ST-002', category:'Breakfast Tacos', name:'Bacon & Egg Taco', price:2.99, description:'Crispy bacon, scrambled egg, cheese', available:true, customizationOptions:JSON.stringify(['Corn Tortilla','Flour Tortilla']) },
      { itemId:'ST-003', category:'Breakfast Tacos', name:'Brisket & Egg Taco', price:3.99, description:'Slow-smoked brisket with scrambled egg', available:true, customizationOptions:JSON.stringify(['Corn Tortilla','Flour Tortilla','Add Salsa']) },
      { itemId:'ST-004', category:'Breakfast Tacos', name:'Bean & Cheese Taco', price:1.99, description:'Refried beans, cheddar cheese', available:true, customizationOptions:JSON.stringify(['Corn Tortilla','Flour Tortilla']) },
      { itemId:'ST-005', category:'Breakfast Tacos', name:'Chorizo & Egg Taco', price:2.99, description:'Spicy chorizo with scrambled egg', available:true, customizationOptions:JSON.stringify(['Corn Tortilla','Flour Tortilla']) },
      { itemId:'ST-006', category:'Breakfast Tacos', name:'Potato & Egg Taco', price:2.50, description:'Seasoned potatoes and scrambled egg', available:true, customizationOptions:JSON.stringify(['Corn Tortilla','Flour Tortilla']) },
      { itemId:'ST-007', category:'Gorditas', name:'Gordita de Chicharrón', price:4.50, description:'Thick corn pocket stuffed with chicharrón in salsa verde', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'ST-008', category:'Gorditas', name:'Gordita de Frijoles', price:3.99, description:'Bean gordita with cheese and crema', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'ST-009', category:'Tortas', name:'Torta de Egg & Chorizo', price:6.99, description:'Bolillo roll with chorizo, egg, beans, avocado', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'ST-010', category:'Tortas', name:'Torta de Brisket', price:7.99, description:'Brisket, refried beans, jalapeño, avocado on bolillo', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'ST-011', category:'Drinks', name:'Agua Fresca', price:2.00, description:'Fresh-made agua fresca — ask for today\'s flavor', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'ST-012', category:'Drinks', name:'Coffee', price:1.50, description:'Hot black coffee', available:true, customizationOptions:JSON.stringify([]) },
    ]
  },
  {
    id: 'DonJuliosTacos', subdomain: 'donjuliostacos',
    name: "Don Julio's Tacos", emoji: '🌮',
    tagline: 'Street Tacos & Breakfast Burritos · Salado, TX',
    heroDesc: 'Classic street tacos and loaded breakfast burritos on FM 1670. Quick, authentic, and worth every mile.',
    about: "Don Julio's Tacos is a no-frills street taco experience parked at the self-service car wash on FM 1670. Known for their mini pastor and bistek tacos and loaded breakfast burritos, this is a Salado morning staple.",
    address: '10071 FM 1670, Salado, TX 76571', phone: '(254) 768-6409',
    hours: [['Mon–Sat','6:30 AM – 2:00 PM'],['Sunday','7:30 AM – 1:00 PM']],
    happyHour: null,
    primary: '#1B5E20', primaryDark: '#145214', accent: '#F59E0B',
    textOnPrimary: '#FFFFFF',
    source: 'DonJuliosTacos', password: 'DonJulios2025!',
    features: ['Street Tacos','Breakfast Burritos','Mini Tacos','Open Daily'],
    categories: ['Mini Tacos','Breakfast','Quesadillas','Drinks'],
    menu: [
      { itemId:'DJ-001', category:'Mini Tacos', name:'Mini Tacos — 5 Pack', price:10.00, description:'5 mini tacos with frijoles charros — pastor or bistek', available:true, customizationOptions:JSON.stringify(['Al Pastor','Bistek']) },
      { itemId:'DJ-002', category:'Mini Tacos', name:'Mini Tacos — 10 Pack', price:20.00, description:'10 mini tacos with frijoles charros — pastor or bistek', available:true, customizationOptions:JSON.stringify(['Al Pastor','Bistek','Mixed']) },
      { itemId:'DJ-003', category:'Mini Tacos', name:'Tacos de Asada', price:3.50, description:'Grilled carne asada street tacos, cilantro & onion', available:true, customizationOptions:JSON.stringify(['Corn Tortilla','Flour Tortilla','Add Salsa']) },
      { itemId:'DJ-004', category:'Breakfast', name:'Breakfast Burrito', price:7.99, description:'Flour tortilla with eggs, chorizo, cheese, and potatoes', available:true, customizationOptions:JSON.stringify(['Chorizo','Bacon','Potato & Egg','Add Jalapeños']) },
      { itemId:'DJ-005', category:'Breakfast', name:'Breakfast Taco', price:2.50, description:'Egg, cheese, and your choice of filling on fresh tortilla', available:true, customizationOptions:JSON.stringify(['Bacon','Chorizo','Potato','Bean & Cheese']) },
      { itemId:'DJ-006', category:'Quesadillas', name:'Quesadilla', price:6.99, description:'Grilled flour tortilla with cheese and protein', available:true, customizationOptions:JSON.stringify(['Cheese Only','Add Asada','Add Pastor']) },
      { itemId:'DJ-007', category:'Drinks', name:'Bottled Water', price:1.00, description:'Cold bottled water', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'DJ-008', category:'Drinks', name:'Soda', price:1.50, description:'Canned soda', available:true, customizationOptions:JSON.stringify(['Coke','Diet Coke','Sprite','Dr Pepper']) },
    ]
  },
  {
    id: 'HechoEnQueso', subdomain: 'hechoenqueso',
    name: 'Hecho en Queso', emoji: '🧀',
    tagline: 'Mexican Fusion · Catering & Events · Salado, TX',
    heroDesc: 'Creative Mexican fusion with vegan, keto, and gluten-free options. Available for catering up to 500 guests.',
    about: "Hecho en Queso brings inventive Mexican fusion to Salado with rotating weekly specials and a commitment to dietary inclusivity. Owners Brooke and Anuar craft everything from classic fajita tacos to their signature chicken banh mi torta — available for dine-in and large-scale catering events.",
    address: 'Salado, TX 76571', phone: '(254) 768-7336',
    hours: [['Wed–Sun','Varies — check Instagram'],['Available','For catering events']],
    happyHour: null,
    primary: '#7C3AED', primaryDark: '#5B21B6', accent: '#F59E0B',
    textOnPrimary: '#FFFFFF',
    source: 'HechoEnQueso', password: 'HechoEnQueso2025!',
    features: ['Mexican Fusion','Vegan & Keto Options','Event Catering','Rotating Specials'],
    categories: ['Tacos', 'Tortas', 'Breakfast', 'Sides', 'Drinks'],
    menu: [
      { itemId:'HEQ-001', category:'Tacos', name:'Fajita Steak Tacos', price:12.99, description:'Grilled fajita steak, onions & peppers, fresh tortillas', available:true, customizationOptions:JSON.stringify(['Corn Tortilla','Flour Tortilla','Keto Lettuce Wrap']) },
      { itemId:'HEQ-002', category:'Tacos', name:'Al Pastor Tacos', price:11.99, description:'Marinated pork pastor with pineapple, cilantro, onion', available:true, customizationOptions:JSON.stringify(['Corn Tortilla','Flour Tortilla']) },
      { itemId:'HEQ-003', category:'Tacos', name:'Vegan Street Tacos', price:10.99, description:'Seasoned black beans, roasted peppers, avocado, pico', available:true, customizationOptions:JSON.stringify(['Corn Tortilla','Flour Tortilla']) },
      { itemId:'HEQ-004', category:'Tortas', name:'Chicken Banh Mi Torta', price:13.99, description:'Korean-inspired chicken, pickled veggies, cilantro, jalapeño aioli', available:true, customizationOptions:JSON.stringify(['Extra Jalapeño','No Spice']) },
      { itemId:'HEQ-005', category:'Tortas', name:'Steak Torta', price:14.99, description:'Fajita steak, beans, avocado, cheese, chipotle mayo', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'HEQ-006', category:'Breakfast', name:'Migas Plate', price:10.99, description:'Scrambled eggs with tortilla chips, peppers, cheese, pico', available:true, customizationOptions:JSON.stringify(['Add Chorizo +$2','Add Avocado +$1']) },
      { itemId:'HEQ-007', category:'Breakfast', name:'Breakfast Burrito', price:11.99, description:'Eggs, bacon, sausage, or chorizo with beans and cheese', available:true, customizationOptions:JSON.stringify(['Bacon','Sausage','Chorizo','Veggie']) },
      { itemId:'HEQ-008', category:'Sides', name:'Chips & Queso', price:6.99, description:'Tortilla chips with house queso, rice, beans, lettuce, tomato', available:true, customizationOptions:JSON.stringify(['Add Protein +$3']) },
      { itemId:'HEQ-009', category:'Sides', name:'Side of Rice & Beans', price:3.99, description:'Mexican rice and refried beans', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'HEQ-010', category:'Drinks', name:'Agua Fresca', price:3.00, description:'Fresh house-made agua fresca', available:true, customizationOptions:JSON.stringify(['Horchata','Jamaica','Tamarindo']) },
    ]
  },
  {
    id: 'HappyPizza', subdomain: 'happypizza',
    name: 'Happy Pizza Company', emoji: '🍕',
    tagline: 'Wood-Fired Sourdough Pizza · Barrow Brewing · Salado, TX',
    heroDesc: 'Hand-crafted 12" sourdough pizzas made from scratch with Barrow Brewing yeast. Order from your table at the biergarten.',
    about: "Happy Pizza Company brings wood-fired sourdough pizza to Barrow Brewing's biergarten. Every 12\" pie is made-to-order with a scratch sourdough crust fermented with Barrow Brewing yeast. From classic Margherita to the adventurous Jallelujah Jalapeño with brie and crème fraiche — there's something for everyone, including vegan options.",
    address: '108 Royal St (Barrow Brewing), Salado, TX 76571', phone: '(254) 226-1684',
    hours: [['Thursday','4:00 PM – 9:00 PM'],['Friday','4:00 PM – 9:30 PM'],['Saturday','11:00 AM – 9:30 PM'],['Sunday','Noon – 8:00 PM']],
    happyHour: null,
    primary: '#CC2936', primaryDark: '#A01F2A', accent: '#1A1A1A',
    textOnPrimary: '#FFFFFF',
    source: 'HappyPizza', password: 'HappyPizza2025!',
    features: ['Wood-Fired Sourdough','Made to Order','Vegan Options','At Barrow Brewing'],
    categories: ['Pizzas', 'Vegan Pizzas', 'Sides'],
    menu: [
      { itemId:'HP-001', category:'Pizzas', name:'No Diggity', price:16.00, description:'Red sauce, signature cheese blend — the classic', available:true, customizationOptions:JSON.stringify(['Regular Crust','GF Crust +$3.50']) },
      { itemId:'HP-002', category:'Pizzas', name:'Margherita', price:17.00, description:'Red sauce, mozzarella, halved tomatoes, fresh basil', available:true, customizationOptions:JSON.stringify(['Regular Crust','GF Crust +$3.50']) },
      { itemId:'HP-003', category:'Pizzas', name:'Pilot', price:17.00, description:'Red sauce, cheese blend, classic pepperoni', available:true, customizationOptions:JSON.stringify(['Regular Crust','GF Crust +$3.50']) },
      { itemId:'HP-004', category:'Pizzas', name:'Holla Back', price:18.00, description:'Olive oil, cheese blend, fresh mozzarella, rosemary', available:true, customizationOptions:JSON.stringify(['Regular Crust','GF Crust +$3.50']) },
      { itemId:'HP-005', category:'Pizzas', name:'Big Don', price:20.00, description:'Red sauce, cheese blend, Canadian bacon, smoked bacon, sausage, caramelized onion', available:true, customizationOptions:JSON.stringify(['Regular Crust','GF Crust +$3.50']) },
      { itemId:'HP-006', category:'Pizzas', name:'Bel-Air', price:19.00, description:'Red sauce, sausage, pepperoni, black olives, mushrooms, red onion, bell pepper', available:true, customizationOptions:JSON.stringify(['Regular Crust','GF Crust +$3.50']) },
      { itemId:'HP-007', category:'Pizzas', name:'Jallelujah Jalapeño', price:20.00, description:'Crème fraiche, brie, bacon, mushroom, purple onion, jalapeño', available:true, customizationOptions:JSON.stringify(['Regular Crust','GF Crust +$3.50']) },
      { itemId:'HP-008', category:'Pizzas', name:'BBQ Chicken', price:19.00, description:'BBQ sauce, chicken, red onion, cheese blend', available:true, customizationOptions:JSON.stringify(['Regular Crust','GF Crust +$3.50']) },
      { itemId:'HP-009', category:'Pizzas', name:'Jackalope', price:18.00, description:'Red sauce, spinach, mushrooms, bacon', available:true, customizationOptions:JSON.stringify(['Regular Crust','GF Crust +$3.50']) },
      { itemId:'HP-010', category:'Pizzas', name:'Chicken Bacon Ranch', price:19.00, description:'Ranch, chicken, bacon, red onion, cheese blend', available:true, customizationOptions:JSON.stringify(['Regular Crust','GF Crust +$3.50']) },
      { itemId:'HP-011', category:'Vegan Pizzas', name:'The Martian (Vegan)', price:18.00, description:'Olive oil, house red sauce, red onion, olives, bell pepper, mushrooms, cherry tomatoes, garlic', available:true, customizationOptions:JSON.stringify(['Regular Crust','GF Crust +$3.50']) },
      { itemId:'HP-012', category:'Vegan Pizzas', name:'Falafel Pizza (Vegan)', price:19.00, description:'Calabrian pepper sauce, red onion, bell pepper, olives, vegan cheese, falafel crumble', available:true, customizationOptions:JSON.stringify(['Regular Crust','GF Crust +$3.50']) },
      { itemId:'HP-013', category:'Sides', name:'Sourdough Pretzel', price:8.00, description:'House-made sourdough pretzel with honey mustard', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'HP-014', category:'Sides', name:'Cheese Stick Pizza', price:14.00, description:'Cheese blend, shaved parm, thyme, roasted garlic EVOO', available:true, customizationOptions:JSON.stringify([]) },
    ]
  },
  {
    id: 'SacredSandwich', subdomain: 'sacredsandwich',
    name: 'Sacred Sandwich', emoji: '🥖',
    tagline: 'Gourmet Sandwiches on Sourdough & Rye · Salado, TX',
    heroDesc: 'Handcrafted gourmet sandwiches on fresh-baked sourdough and rye. Parked at Barrow Brewing biergarten.',
    about: "Sacred Sandwich elevates the humble sandwich to an art form. Every build is thoughtfully crafted on fresh sourdough or rye — from the MexItalian loaded with pastrami and salami to the classic Reuben dripping with Swiss and thousand island. Located at Barrow Brewing's biergarten, pair your sandwich with a cold craft beer.",
    address: '108 Royal St (Barrow Brewing), Salado, TX 76571', phone: null,
    hours: [['Wed–Sun','Open at Barrow Brewing hours']],
    happyHour: null,
    primary: '#1B5E6B', primaryDark: '#144A55', accent: '#D4A843',
    textOnPrimary: '#FFFFFF',
    source: 'SacredSandwich', password: 'Sacred2025!',
    features: ['Sourdough & Rye','Gourmet Builds','Online Ordering','At Barrow Brewing'],
    categories: ['Sandwiches', 'Sides', 'Drinks'],
    menu: [
      { itemId:'SS-001', category:'Sandwiches', name:'MexItalian', price:12.00, description:'Pastrami, salami, pepperoni, Oaxaca cheese, cilantro, tomatoes, red onion, balsamic vinaigrette on sourdough', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SS-002', category:'Sandwiches', name:'Cubano', price:12.00, description:'Ham, bacon, Swiss, pickles, mustard on sourdough', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SS-003', category:'Sandwiches', name:'Turkey Bacon Pesto', price:12.00, description:'Turkey, bacon, basil pesto, provolone, lettuce, tomato, red onion on sourdough', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SS-004', category:'Sandwiches', name:'Reuben', price:12.00, description:'Pastrami, sauerkraut, Swiss, thousand island on rye', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SS-005', category:'Sandwiches', name:'Milano Frio', price:12.00, description:'Ham, salami, pepperoni, provolone, lettuce, tomato, red onion, pickles, mayo, mustard on sourdough', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SS-006', category:'Sandwiches', name:'Sliced Turkey', price:12.00, description:'Turkey, Swiss, lettuce, tomato, red onion, mayo, mustard on sourdough', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SS-007', category:'Sides', name:'Premium Baked Potato Salad', price:4.50, description:'House-made loaded baked potato salad', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SS-008', category:'Sides', name:'Creamy Cole Slaw', price:4.00, description:'House-made creamy cole slaw', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SS-009', category:'Sides', name:'Chips / Veggie Straws', price:2.77, description:'Chips or veggie straws', available:true, customizationOptions:JSON.stringify(['Chips','Veggie Straws','Goldfish']) },
      { itemId:'SS-010', category:'Drinks', name:'Soda', price:2.77, description:'Canned soda', available:true, customizationOptions:JSON.stringify(['Coke','Coke Zero','Dr Pepper','Sprite']) },
      { itemId:'SS-011', category:'Drinks', name:'Water', price:2.77, description:'Bottled water', available:true, customizationOptions:JSON.stringify([]) },
    ]
  },
  {
    id: 'ThatGreenTrailer', subdomain: 'thatgreentrailer',
    name: 'That Green Trailer', emoji: '🍔',
    tagline: 'Burgers · Sandwiches · Catering · Salado, TX',
    heroDesc: 'Scratch-made burgers and sandwiches from the iconic green trailer on FM 2484. Available for events up to 500 guests.',
    about: "That Green Trailer has been serving Salado quality comfort food from their signature green trailer on FM 2484. From hand-packed smash burgers to club sandwiches and Asian-inspired dishes, everything is made fresh to order. They also offer full catering services for events up to 500 guests.",
    address: '3366 FM 2484, Salado, TX 76571', phone: '(254) 563-9095',
    hours: [['Thu–Fri','10:00 AM – 1:30 PM'],['Events','By appointment']],
    happyHour: null,
    primary: '#2D6A4F', primaryDark: '#1B4332', accent: '#52B788',
    textOnPrimary: '#FFFFFF',
    source: 'ThatGreenTrailer', password: 'GreenTrailer2025!',
    features: ['Fresh-Ground Burgers','Gourmet Sandwiches','Event Catering','Online Ordering'],
    categories: ['Burgers', 'Sandwiches', 'Sides', 'Drinks'],
    menu: [
      { itemId:'TGT-001', category:'Burgers', name:'Original Burger', price:10.99, description:'Ground chuck, American cheese, onion, lettuce, secret sauce', available:true, customizationOptions:JSON.stringify(['No Onion','Add Bacon +$2','Extra Cheese +$1']) },
      { itemId:'TGT-002', category:'Burgers', name:'Bacon Cheeseburger', price:12.99, description:'Ground chuck, applewood smoked bacon, American cheese, lettuce', available:true, customizationOptions:JSON.stringify(['Add Jalapeños','No Lettuce']) },
      { itemId:'TGT-003', category:'Burgers', name:'Mushroom Swiss Burger', price:12.99, description:'Ground chuck, Swiss cheese, sautéed mushrooms, secret sauce', available:true, customizationOptions:JSON.stringify(['Add Bacon +$2']) },
      { itemId:'TGT-004', category:'Sandwiches', name:'Club Sandwich', price:11.99, description:'Triple-decker with turkey, bacon, ham, lettuce, tomato, mayo', available:true, customizationOptions:JSON.stringify(['No Mayo','Add Avocado +$1']) },
      { itemId:'TGT-005', category:'Sandwiches', name:'Asian Chicken Sandwich', price:12.99, description:'Crispy or grilled chicken with Asian slaw, sriracha aioli', available:true, customizationOptions:JSON.stringify(['Crispy','Grilled','Extra Sauce']) },
      { itemId:'TGT-006', category:'Sides', name:'Fries', price:3.99, description:'Fresh-cut seasoned fries', available:true, customizationOptions:JSON.stringify(['Regular','Loaded +$2']) },
      { itemId:'TGT-007', category:'Sides', name:'Onion Rings', price:4.99, description:'Beer-battered onion rings', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'TGT-008', category:'Drinks', name:'Fountain Drink', price:2.99, description:'Your choice of soda', available:true, customizationOptions:JSON.stringify(['Coke','Diet Coke','Sprite','Dr Pepper','Lemonade']) },
    ]
  },
  {
    id: 'BigTonys', subdomain: 'bigtonys',
    name: "Big Tony's Cheesesteaks", emoji: '🥩',
    tagline: 'West Philly Cheesesteaks · Salado, TX',
    heroDesc: "Authentic Philly cheesesteaks made with shaved ribeye on Amoroso rolls flown in from Philadelphia. 29 varieties.",
    about: "Big Tony's brings a genuine taste of West Philadelphia to Central Texas. Every cheesesteak is built on Amoroso rolls — the real deal, flown in from Philly — with shaved ribeye or chicken and your choice of provolone, whiz, or American. With 29 varieties and gluten-free options, there's a steak for everyone.",
    address: 'Salado, TX (Mobile — check social for location)', phone: null,
    hours: [['Events & Pop-Ups','Check Instagram & Facebook']],
    happyHour: null,
    primary: '#1A3A6B', primaryDark: '#112448', accent: '#F4C842',
    textOnPrimary: '#FFFFFF',
    source: 'BigTonys', password: 'BigTonys2025!',
    features: ['Amoroso Rolls from Philly','Shaved Ribeye','29 Varieties','Gluten-Free Buns'],
    categories: ['Cheesesteaks', 'Chicken Steaks', 'Sides', 'Drinks'],
    menu: [
      { itemId:'BT-001', category:'Cheesesteaks', name:'Classic Philly Cheesesteak', price:14.99, description:'Shaved ribeye, grilled onions, choice of provolone, whiz, or American on Amoroso roll', available:true, customizationOptions:JSON.stringify(['Provolone','Cheese Whiz','American','Add Peppers','Add Mushrooms']) },
      { itemId:'BT-002', category:'Cheesesteaks', name:'The Kelly Drive', price:17.99, description:'Steak, bacon, Italian sausage, chicken, extra cheese, mozzarella sticks, sautéed onions', available:true, customizationOptions:JSON.stringify(['Provolone','Cheese Whiz','American']) },
      { itemId:'BT-003', category:'Cheesesteaks', name:'BBQ Cheesesteak', price:15.99, description:'Shaved ribeye, BBQ sauce, caramelized onions, cheddar', available:true, customizationOptions:JSON.stringify(['Add Jalapeños','Extra BBQ']) },
      { itemId:'BT-004', category:'Cheesesteaks', name:'Buffalo Cheesesteak', price:15.99, description:'Shaved ribeye, buffalo sauce, blue cheese crumbles, celery', available:true, customizationOptions:JSON.stringify(['Mild','Hot','Extra Hot']) },
      { itemId:'BT-005', category:'Chicken Steaks', name:'Classic Chicken Cheesesteak', price:13.99, description:'Shaved chicken, grilled onions, choice of cheese on Amoroso roll', available:true, customizationOptions:JSON.stringify(['Provolone','Cheese Whiz','American']) },
      { itemId:'BT-006', category:'Chicken Steaks', name:'Chicken Buffalo Steak', price:14.99, description:'Shaved chicken, buffalo sauce, blue cheese, celery', available:true, customizationOptions:JSON.stringify(['Mild','Hot']) },
      { itemId:'BT-007', category:'Sides', name:'Sweet Potato Fries', price:5.99, description:'Crispy sweet potato fries with dipping sauce', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'BT-008', category:'Sides', name:'Onion Straws', price:4.99, description:'Crispy fried onion straws', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'BT-009', category:'Sides', name:'Mozzarella Sticks', price:5.99, description:'Golden fried mozzarella with marinara', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'BT-010', category:'Drinks', name:'Soda', price:2.99, description:'Fountain drink', available:true, customizationOptions:JSON.stringify(['Coke','Diet Coke','Sprite','Dr Pepper']) },
    ]
  },
  {
    id: 'PotatoWagon', subdomain: 'potatowagon',
    name: 'Potato Wagon', emoji: '🍗',
    tagline: 'Southern Fried Chicken & Loaded Potatoes · Salado, TX',
    heroDesc: 'Crispy southern fried chicken tenders and gourmet loaded baked potatoes. Comfort food done right.',
    about: "Potato Wagon serves up Southern comfort food at its finest — golden crispy fried chicken tenders and show-stopping loaded baked potatoes. From the classic loaded potato with all the fixings to a buffalo chicken-topped spud, every order is a full meal worth savoring.",
    address: 'Salado, TX 76571', phone: null,
    hours: [['Varies','Check Facebook & Twitter @realpotatowagon']],
    happyHour: null,
    primary: '#7B3F00', primaryDark: '#5A2D00', accent: '#FF8C00',
    textOnPrimary: '#FFFFFF',
    source: 'PotatoWagon', password: 'PotatoWagon2025!',
    features: ['Southern Fried Chicken','Loaded Baked Potatoes','Family Meals','Made to Order'],
    categories: ['Chicken', 'Loaded Potatoes', 'Sides', 'Drinks'],
    menu: [
      { itemId:'PW-001', category:'Chicken', name:'6 Tender Meal', price:12.99, description:'6 crispy tenders, 1 side, gravy, roll, and drink', available:true, customizationOptions:JSON.stringify(['Original','Spicy','Honey Butter']) },
      { itemId:'PW-002', category:'Chicken', name:'3-Piece Fried Chicken', price:10.99, description:'3 pieces fried chicken, 1 side, roll, and drink', available:true, customizationOptions:JSON.stringify(['Original','Spicy']) },
      { itemId:'PW-003', category:'Chicken', name:'2-Piece Fried Chicken', price:8.99, description:'2 pieces fried chicken, 1 side, roll, and drink', available:true, customizationOptions:JSON.stringify(['Original','Spicy']) },
      { itemId:'PW-004', category:'Chicken', name:'Family Meal — 20 Tenders', price:43.84, description:'20 tenders, 2 family sides, family gravy, 5 rolls', available:true, customizationOptions:JSON.stringify(['Original','Spicy','Mixed']) },
      { itemId:'PW-005', category:'Loaded Potatoes', name:'Classic Loaded Potato', price:9.99, description:'Baked potato with butter, sour cream, cheddar, bacon bits, chives', available:true, customizationOptions:JSON.stringify(['Extra Cheese','Extra Bacon']) },
      { itemId:'PW-006', category:'Loaded Potatoes', name:'Buffalo Chicken Potato', price:11.99, description:'Baked potato topped with buffalo chicken, blue cheese, celery', available:true, customizationOptions:JSON.stringify(['Mild','Hot','Extra Hot']) },
      { itemId:'PW-007', category:'Loaded Potatoes', name:'Beef Chili Potato', price:11.99, description:'Baked potato with hearty beef chili, cheddar, sour cream', available:true, customizationOptions:JSON.stringify(['Extra Chili +$1']) },
      { itemId:'PW-008', category:'Loaded Potatoes', name:'Meatballs Marinara Potato', price:11.99, description:'Baked potato with meatballs, marinara, mozzarella', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'PW-009', category:'Sides', name:'Mac & Cheese', price:3.99, description:'Creamy house-made mac & cheese', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'PW-010', category:'Sides', name:'Corn Nuggets', price:3.99, description:'Crispy deep-fried corn nuggets', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'PW-011', category:'Sides', name:'Coleslaw', price:2.99, description:'Creamy southern coleslaw', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'PW-012', category:'Drinks', name:'Fountain Drink', price:2.99, description:'Your choice of soda', available:true, customizationOptions:JSON.stringify(['Coke','Diet Coke','Sprite','Dr Pepper']) },
    ]
  },
  {
    id: 'RibTips', subdomain: 'ribtips',
    name: 'Rib Tips & Catering', emoji: '🔥',
    tagline: 'Soul Food BBQ · Catering · Salado, TX',
    heroDesc: 'Slow-smoked ribs, brisket, and loaded baked potatoes. Soul food and Texas BBQ done the right way.',
    about: "Rib Tips & Catering brings soul food to the Salado BBQ scene. Every rack of ribs and brisket is slow-smoked to perfection, and their loaded stuffed baked potatoes are a meal in themselves. Available for full-service catering events.",
    address: '5889 FM 3481, Salado, TX 76571', phone: '(512) 661-7548',
    hours: [['Mon, Wed, Fri, Sat','Noon – 8:00 PM'],['Tue, Thu','Closed']],
    happyHour: null,
    primary: '#1A1A1A', primaryDark: '#111111', accent: '#CC2936',
    textOnPrimary: '#FFFFFF',
    source: 'RibTips', password: 'RibTips2025!',
    features: ['Slow-Smoked BBQ','Soul Food Sides','Loaded Potatoes','Catering Available'],
    categories: ['BBQ', 'Sandwiches', 'Loaded Potatoes', 'Sides', 'Drinks'],
    menu: [
      { itemId:'RT-001', category:'BBQ', name:'Smoked Rib Plate', price:18.99, description:'Half rack of slow-smoked ribs with 2 sides', available:true, customizationOptions:JSON.stringify(['Dry Rub','BBQ Sauce','Extra Sauce +$1']) },
      { itemId:'RT-002', category:'BBQ', name:'Brisket Plate', price:17.99, description:'Slow-smoked sliced brisket with 2 sides', available:true, customizationOptions:JSON.stringify(['Lean','Fatty','Mixed']) },
      { itemId:'RT-003', category:'BBQ', name:'Rib Tips Plate', price:14.99, description:'Tender smoked rib tips with 2 sides', available:true, customizationOptions:JSON.stringify(['Dry Rub','BBQ Sauce']) },
      { itemId:'RT-004', category:'Sandwiches', name:'Pulled Pork Sandwich', price:10.99, description:'Slow-smoked pulled pork on brioche with coleslaw', available:true, customizationOptions:JSON.stringify(['Add Jalapeños','Extra Sauce']) },
      { itemId:'RT-005', category:'Sandwiches', name:'Brisket Sandwich', price:12.99, description:'Sliced brisket on brioche with pickles and onions', available:true, customizationOptions:JSON.stringify(['Extra Brisket +$3']) },
      { itemId:'RT-006', category:'Loaded Potatoes', name:'BBQ Loaded Potato', price:10.99, description:'Baked potato with pulled pork, BBQ sauce, cheddar, sour cream', available:true, customizationOptions:JSON.stringify(['Add Brisket +$3']) },
      { itemId:'RT-007', category:'Sides', name:'Mac & Cheese', price:3.99, description:'Creamy smoked mac & cheese', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'RT-008', category:'Sides', name:'Baked Beans', price:3.99, description:'Slow-cooked BBQ baked beans', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'RT-009', category:'Sides', name:'Potato Salad', price:3.99, description:'Southern-style potato salad', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'RT-010', category:'Drinks', name:'Sweet Tea', price:2.99, description:'House-brewed sweet tea', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'RT-011', category:'Drinks', name:'Soda', price:2.99, description:'Canned soda', available:true, customizationOptions:JSON.stringify(['Coke','Diet Coke','Sprite','Dr Pepper']) },
    ]
  },
  {
    id: 'SimplyPorkFection', subdomain: 'simplyporkfection',
    name: 'Simply Pork Fection', emoji: '🍖',
    tagline: 'Specialty BBQ & Smoked Meats · Salado, TX',
    heroDesc: 'Perfectly smoked meats with one-of-a-kind specialty sides. BBQ the way it was meant to be.',
    about: "Simply Pork Fection sets itself apart with its truly unique specialty sides and perfectly smoked meats. Whether it's fall-off-the-bone ribs or slow-pulled pork, every plate is a testament to patience and craft. Available for weddings and large events.",
    address: 'Salado, TX 76571', phone: '(512) 466-3102',
    hours: [['Mon–Wed','10:30 AM – 2:00 PM'],['Fri','4:00 PM – 10:00 PM'],['Sat','5:00 PM – 10:00 PM'],['Sun','10:30 AM – 5:00 PM']],
    happyHour: null,
    primary: '#8B2500', primaryDark: '#6B1C00', accent: '#F59E0B',
    textOnPrimary: '#FFFFFF',
    source: 'SimplyPorkFection', password: 'PorkFection2025!',
    features: ['Slow-Smoked Meats','Specialty Sides','Wedding Catering','Text to Order'],
    categories: ['BBQ Plates', 'Sandwiches', 'Sides', 'Drinks'],
    menu: [
      { itemId:'SPF-001', category:'BBQ Plates', name:'Pulled Pork Plate', price:14.99, description:'Slow-smoked pulled pork with 2 specialty sides', available:true, customizationOptions:JSON.stringify(['Dry','Sauced','Extra Sauce +$1']) },
      { itemId:'SPF-002', category:'BBQ Plates', name:'Rib Plate', price:18.99, description:'Half rack of smoked ribs with 2 specialty sides', available:true, customizationOptions:JSON.stringify(['Baby Back','Spare Rib']) },
      { itemId:'SPF-003', category:'BBQ Plates', name:'Smoked Meat Sampler', price:22.99, description:'Pulled pork, rib tips, and smoked sausage with 2 sides', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SPF-004', category:'Sandwiches', name:'Pulled Pork Sandwich', price:10.99, description:'Slow-smoked pulled pork on brioche with specialty slaw', available:true, customizationOptions:JSON.stringify(['Extra Meat +$3','Add Jalapeños']) },
      { itemId:'SPF-005', category:'Sides', name:'Specialty Side #1', price:3.99, description:'Ask about today\'s specialty side — changes regularly', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SPF-006', category:'Sides', name:'Specialty Side #2', price:3.99, description:'Second rotating specialty side — always unique', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SPF-007', category:'Sides', name:'Classic Coleslaw', price:2.99, description:'Creamy house slaw', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SPF-008', category:'Drinks', name:'Sweet Tea', price:2.99, description:'Southern sweet tea', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SPF-009', category:'Drinks', name:'Soda', price:2.99, description:'Canned soda', available:true, customizationOptions:JSON.stringify(['Coke','Diet Coke','Dr Pepper','Sprite']) },
    ]
  },
  {
    id: 'BobbyQue', subdomain: 'bobbyque',
    name: 'BobbyQue', emoji: '🥩',
    tagline: 'Texas BBQ Brisket · Barrow Brewing Biergarten · Salado, TX',
    heroDesc: 'Serious Texas BBQ — slow-smoked brisket, burnt ends, and all the fixings at the Barrow Brewing Biergarten.',
    about: "BobbyQue is Salado's BBQ answer at Barrow Brewing's biergarten. Slow-smoked Central Texas style — thick sliced brisket, charred burnt ends, and beef that's been earning its smoke ring for hours. Pair with a cold craft beer from Barrow for the full experience.",
    address: '108 Royal St (Barrow Brewing Biergarten), Salado, TX 76571', phone: null,
    hours: [['Thu–Sun','Per Barrow Brewing hours — seasonal, closed Dec–Jan']],
    happyHour: null,
    primary: '#0D0D0D', primaryDark: '#000000', accent: '#D32F2F',
    textOnPrimary: '#FFFFFF',
    source: 'BobbyQue', password: 'BobbyQue2025!',
    features: ['Central Texas Brisket','Burnt Ends','At Barrow Brewing','Seasonal Hours'],
    categories: ['BBQ', 'Sandwiches', 'Sides', 'Drinks'],
    menu: [
      { itemId:'BQ-001', category:'BBQ', name:'Brisket Plate', price:18.99, description:'Thick-sliced slow-smoked brisket with 2 sides', available:true, customizationOptions:JSON.stringify(['Lean','Fatty','Mixed']) },
      { itemId:'BQ-002', category:'BBQ', name:'Burnt Ends Plate', price:20.99, description:'Charred brisket burnt ends — caramelized, smoky, rich', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'BQ-003', category:'BBQ', name:'Beef Slices Plate', price:16.99, description:'Classic beef slices, Texas style, with 2 sides', available:true, customizationOptions:JSON.stringify(['Lean','Fatty']) },
      { itemId:'BQ-004', category:'Sandwiches', name:'Brisket Sandwich', price:13.99, description:'Sliced brisket on white bread with pickles, onions, sauce', available:true, customizationOptions:JSON.stringify(['Extra Sauce','No Onion']) },
      { itemId:'BQ-005', category:'Sandwiches', name:'Burnt Ends Sandwich', price:14.99, description:'Burnt ends on brioche with BBQ sauce and pickled onions', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'BQ-006', category:'Sides', name:'Pinto Beans', price:3.99, description:'Slow-cooked Texas pinto beans', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'BQ-007', category:'Sides', name:'Creamed Corn', price:3.99, description:'Rich Texas-style creamed corn', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'BQ-008', category:'Sides', name:'Potato Salad', price:3.99, description:'Classic Texas potato salad', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'BQ-009', category:'Drinks', name:'Sweet Tea', price:2.99, description:'Fresh-brewed sweet tea', available:true, customizationOptions:JSON.stringify([]) },
    ]
  },
  {
    id: 'SodaFusion', subdomain: 'sodafusion',
    name: 'Soda Fusion', emoji: '🥤',
    tagline: 'Specialty Drinks & Loaded Hot Dogs · Salado, TX',
    heroDesc: 'Hand-crafted specialty sodas, loaded hot dogs, and loaded fries. Creative flavors you won\'t find anywhere else.',
    about: "Soda Fusion is Salado's most creative food truck — hand-blending specialty sodas with cold brew and iced tea steeped in-house for 16 hours, paired with a lineup of loaded hot dogs and loaded fries that defy expectations. Come for the drinks, stay for the food.",
    address: 'Salado, TX 76571', phone: '(812) 391-4403',
    hours: [['Varies','Check social media for current location & hours']],
    happyHour: null,
    primary: '#6200EA', primaryDark: '#4A00B4', accent: '#00BCD4',
    textOnPrimary: '#FFFFFF',
    source: 'SodaFusion', password: 'SodaFusion2025!',
    features: ['Specialty Blended Sodas','16-Hour Cold Brew','Loaded Hot Dogs','Custom Creations'],
    categories: ['Specialty Drinks', 'Loaded Hot Dogs', 'Loaded Fries & Sides'],
    menu: [
      { itemId:'SF-001', category:'Specialty Drinks', name:'Specialty Blended Soda', price:5.99, description:'Custom-blended specialty soda — ask for today\'s creations', available:true, customizationOptions:JSON.stringify(['Classic','Tropical','Berry Blast','Citrus Fusion']) },
      { itemId:'SF-002', category:'Specialty Drinks', name:'16-Hour Cold Brew', price:5.99, description:'Cold brew steeped in-house for 16 hours — smooth and rich', available:true, customizationOptions:JSON.stringify(['Black','Sweet Cream','Vanilla','Caramel']) },
      { itemId:'SF-003', category:'Specialty Drinks', name:'16-Hour Iced Tea', price:4.99, description:'Iced tea steeped in-house for 16 hours', available:true, customizationOptions:JSON.stringify(['Sweet','Unsweet','Half & Half','Peach','Raspberry']) },
      { itemId:'SF-004', category:'Specialty Drinks', name:'Specialty Lemonade', price:5.49, description:'Fresh-squeezed lemonade with house blend flavoring', available:true, customizationOptions:JSON.stringify(['Classic','Strawberry','Mango','Lavender']) },
      { itemId:'SF-005', category:'Loaded Hot Dogs', name:'Classic Loaded Dog', price:7.99, description:'All-beef hot dog with mustard, ketchup, onions, relish', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SF-006', category:'Loaded Hot Dogs', name:'Bacon Chili Dog', price:9.99, description:'All-beef dog with beef chili, cheddar, bacon, jalapeños', available:true, customizationOptions:JSON.stringify(['Extra Chili','Extra Jalapeños']) },
      { itemId:'SF-007', category:'Loaded Hot Dogs', name:'Mac & Cheese Dog', price:9.99, description:'All-beef dog topped with creamy mac & cheese and bacon bits', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SF-008', category:'Loaded Hot Dogs', name:'BBQ Brisket Dog', price:10.99, description:'All-beef dog with chopped brisket, BBQ sauce, crispy onions', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SF-009', category:'Loaded Fries & Sides', name:'Loaded Fries', price:8.99, description:'Fries loaded with cheese sauce, bacon, jalapeños, sour cream', available:true, customizationOptions:JSON.stringify(['Add Chili +$2','Add Brisket +$3']) },
      { itemId:'SF-010', category:'Loaded Fries & Sides', name:'Loaded Tots', price:8.99, description:'Crispy tots with cheese sauce, bacon, ranch drizzle', available:true, customizationOptions:JSON.stringify([]) },
      { itemId:'SF-011', category:'Loaded Fries & Sides', name:'Chicken Tenders', price:8.99, description:'3 crispy chicken tenders with dipping sauce', available:true, customizationOptions:JSON.stringify(['Ranch','Honey Mustard','BBQ','Buffalo']) },
    ]
  },
];

module.exports = { trucks, APPSYNC_URL, API_KEY };
